### PR TITLE
Migration with create-react-app typescript

### PR DESCRIPTION
**Pull request by Umapreethi-G**
Hi CreativeTim Team,

As mentioned in the https://github.com/creativetimofficial/material-kit-react/issues/55, we have migrated this project with react typescript.

If you need to have this pr in a different branch, please create a separate branch and let us know. So that, we will point this pr to that particular branch.

### CODE REVIEW

**Comment by EINazare** [comment]
Hello there, @Umapreethi-G ,

I've added the branch "customer-support".
We will keep that branch for PR's.
I am not sure how we will keep our current code and your code as well.
I believe that we cannot have both typescript and babel right?
Maybe we will have two folders, one with Babel and one with TypeScrpit.
Anyway, you can go ahead and make the PR for that branch.

Best,
Manu

**Comment by Umapreethi-G** [comment]
Hi @EINazare, PR is changed to point "customer-support". Actually this project supports both typescript and babel. Verify whether it matches the existing code base and let us know if anything is missing. Thanks :)

**Comment by EINazare** [comment]
Hello there, @Umapreethi-G ,

I will take a look tomorrow morning and come back here with a response.
If everything works fine, I will accept your PR, if not, I will tell you why the PR will not be accepted. Hope this is ok with you.

Best,
Manu

**Comment by fullhdpixel** [comment]
I tried adding it to my project but it says: "Cannot find module: /client/Libs/material-component/src/components/Badge/Badge'". I have a reproduction of it here: https://github.com/fullhdpixel/kamermaatje. Maybe you can help me @Umapreethi-G ?

**Comment by Umapreethi-G** [comment]
Hai @EINazare ,
                     Thanks for approving my PR.

**Comment by EINazare** [comment]
Hello again, @Umapreethi-G ,

Will move that branch into the master one, or maybe a new one only for typescript, once we figure out how to keep both TypeScript and Babel :) .

Best,
Manu

**Comment by tokomeno** [comment]
Hello, thanks @EINazare for the great theme and @Umapreethi-G  for adding the typescript version.

I'm just interested in if typescript version up to date with master and if u are willing to support the typescript version as the main one?

**Comment by EINazare** [comment]
Hello there, @tokomeno ,

> I'm just interested in if typescript version up to date with master and if u are willing to support the typescript version as the main one?

If this question is for me (i.e. Creative Tim), the answer is no, we cannot offer support for a product that is not ours.
We wish next year to start adding TypeScript & React themes on our marketplace - note, there is a 87% change that there will be two products Material Kit React, and Material Kit React TypeScript, i.e. we will have the Babel and TypeScript versions as separate.

Best,
Manu

**Pull request merged**
